### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by wkarl** [davidmoten/rxjava-file#15]
Not all java.nio classes are available on Android:
`java.lang.NoClassDefFoundError: Failed resolution of: [Ljava/nio/file/WatchEvent$Kind;`

Would it be possible to make this platform independent?

**Comment by davidmoten** [comment]
Don't know.  Can you do the research?

**Comment by wkarl** [comment]
Okay I'll have a look!

**Comment by wkarl** [comment]
Unfortunately Android uses a platform specific FileObserver to watch for file changes:
https://developer.android.com/reference/android/os/FileObserver.html
