### ISSUE TITLE
Support for latest RxJava 2.x

### ISSUE THREAD

**Issue by corporatepiyush** [davidmoten/rxjava-file#17]
It's been almost 2 years since v2.x release of RxJava and its also widely adopted than 1.x

It would be great if this library supports latest version of RxJava

**Comment by davidmoten** [comment]
Fair enough, I'll have a look.

**Comment by toaler** [comment]
@davidmoten what is the plan to make RxJava 2.x compatible?

**Comment by davidmoten** [comment]
@toaler having a look now, new library will be at https://github.com/davidmoten/rxjava2-file

**Comment by corporatepiyush** [comment]
Awesome. Thanks David

**Comment by toaler** [comment]
Thanks @davidmoten giving it a go.
