### ISSUE TITLE
Interaction with standard operators

### ISSUE THREAD

**Issue by mredaelli** [davidmoten/rxjava-file#6]
I have the following setup:

        File file = new File(".\\server.log");
        Observable<String> newLines =
                FileObservable.tailer()
                        .file(file)
                        .startPosition(file.length())
                        .sampleTimeMs(1000)
                        .chunkSize(8192)
                        .utf8()
                        .tailText();

        newLines.subscribe(System.out::println);

and it works as expected.
But as soon as I try to chain some more operators, I get problems. For instance, changing to

      newLines.filter(LogfileWatcher::error).subscribe(System.out::println);

(where `error()` is a simple function `String -> Boolean`) I get output only after the first append to the file, but not the subsequent ones.
Similar problems appear when using `window()` or several other operators. For instance, using the `byLine()` function as suggested in the docs results in no output at all:

        Observable<String> newLines1 = StringObservable.split(newLines, "\n");
        newLines1.subscribe(System.out::println);

I'm very new to RX, so I don't know if I'm doing something wrong, though...

**Comment by davidmoten** [comment]
Ah sorry, I didn't notice this issue in my github feed

**Comment by davidmoten** [comment]
What OS are you on?

**Comment by mredaelli** [comment]
Windows 7, I'm afraid :)

**Comment by davidmoten** [comment]
Might be worth a try to use the new backpressure supporting version 0.3.3 that should be available on Maven Central in an hour or so (might be there now). Fixed tests to run on Windows and noticed that windows is more fussy about what will trigger events.

**Comment by mredaelli** [comment]
It seems to be working! Thanks :+1:
