### ISSUE TITLE
StringObservable required?

### ISSUE THREAD

**Issue by ayedo** [davidmoten/rxjava-file#9]
Hi, 

first: thanks for your great work!

In the documentation you note:

[...] if you want the Observable<String> to be emitting line by line then wrap it with a call like StringObservable.split(observable, "\n"). [...]

Is this still required? I saw in the source code that tailText calls a function "toLines". Does this call do something different? Why is StringObservable required?

**Comment by davidmoten** [comment]
Thanks for that. No not required now because of the dependency on rxjava-extras that has a backpressure supporting version of split. I'll update the doco.
